### ISSUE TITLE
Admin account create/modify/delete not sending emails

### ISSUE THREAD

**Issue by skione** [nexcess/magento-alarmbell#13]
Admin logins are working but I am not getting the notification email when admin accounts are created or modified. Could you please advise? I checked the outbound mail log on the server and I can see the email being sent for logins but no trace on create. Let me know if you need any info.

**Comment by aricwatson** [comment]
Yes - this PR https://github.com/nexcess/magento-alarmbell/pull/9 should fix the issue - it's been merged into the devel branch, we'll probably update it to master this week.

**Comment by JonnaIsaac01** [comment]
Hi,

I am also experiencing this issue. Successful and failed logins are sending notifications and logging to system.log, however changes to admin account aren't (neither notifications nor system.log). I downloaded the extension today, so it should be current.

Thanks!

**Comment by aricwatson** [comment]
Please try grabbing the _devel_ branch from this site for the fix. We haven't merged it to master and updated Magento connect yet. Sorry for the hassle.

**Comment by skione** [comment]
We are using the mod in this branch and it corrects this issue. I would think this should get merged to master asap. We can confirm it is running on many clients successfully.

**Comment by JonnaIsaac01** [comment]
When do you expect to merge it into master? I want to be sure it's stable before installing on our client's site.

Thanks!

**Comment by aricwatson** [comment]
> We can confirm it is running on many clients successfully.

Excellent, was hoping to hear something like this :)

I'll merge it into master today.

**Comment by aricwatson** [comment]
I've merged dev into master.
